name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.18.0-chrome107-ff106-edge
    steps:
      - run: echo "Hello, world!"
