name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    container:
      image: node-16.18.1-chrome-107.0.5304.121-1-ff-107.0-edge-100.0.1185.29-1
    steps:
      - run: echo "Hello, world!"
