name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.17.0-chrome-128.0.6613.137-1-ff-130.0.1-edge-128.0.2739.67-1
    steps:
      - run: echo "Hello, world!"
