name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.13.0-chrome-143.0.7499.192-1-ff-147.0-edge-143.0.3650.139-1
    steps:
      - run: echo "Hello, world!"
