name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
    steps:
      - run: echo "Hello, world!"
