name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.16.0-chrome-136.0.7103.113-1-ff-139.0.1-edge-136.0.3240.76-1
    steps:
      - run: echo "Hello, world!"
